'use strict'

// tests for uploader
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin')
const expect = mochaPlugin.chai.expect
let wrapped = mochaPlugin.getWrapper('uploader', '/src/uploader.js', 'handler')

describe('uploader', () => {
  before((done) => {
    done()
  })

  it('it should require an image supplied in the request body', () => {
    const result = 'A JSON object with a base64 image is required in the request body to use this service.'
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty
      expect(response.statusCode).to.equal(400)
      expect(response.body).to.be.eql(result)
    })
  })
})
